# Orb 'cypress-io/cypress@1' resolved to 'cypress-io/cypress@1.7.0'
version: 2
jobs:
  cypress/run:
    docker:
    - image: cypress/base:10
    parallelism: 1
    steps:
    - checkout
    - restore_cache:
        keys:
        - cache2-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Check if package-lock.json exists
        command: |
          if [ ! -e ./package-lock.json ]; then
            echo "The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'."
            echo "A 'package-lock.json' file was not found. Please run 'npm install' in your project,"
            echo "and commit 'package-lock.json' to your repo."
            exit 1
          fi
    # to enable npm postinstall
    - run: npm config set unsafe-perm true
    - run:
        name: Npm CI
        command: npm ci
    - save_cache:
        key: cache2-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.npm
        - ~/.cache
    - run:
        name: tests one
        command: npm test
        working_directory: one
    - run:
        name: tests two
        command: npm test
        working_directory: two
workflows:
  build:
    jobs:
    - cypress/run
  version: 2
